variant-calls:
  # Listing of callsets and corresponding paths, representing variant call results
  # from different pipelines or different configurations of the same pipeline.
  # Multiple entries are possible.
  <callset>: 
    # Optional labels to describe callset in report. Comment out if not needed.
    # Both labels and values thereof can be freely chosen.
    labels:
      caller: freebayes
      site: University of Duisburg-Essen
    # Optional subcategory for separating callsets in the report. Comment out if not needed.
    subcategory: agilent
    path: <path>
    # benchmark to use (giab-NA12878-exome or any custom benchmark name provided from below)
    benchmark: giab-na12878-exome
    # Uncomment and point to file containing contig name replacements
    # as needed for 'bcftools annotate --rename-chrs'
    # rename-contigs: path/to/rename-contigs.txt

# Optional custom benchmarks
custom-benchmarks:
  my-custom-benchmark: # custom benchmark name, choose freely (no whitespace allowed)
    # Truth genome to consider (for now only NA12878 allowed, TODO: CHM)
    genome: na12878
    # Path to fastqs with the reads used for variant calling (alternatively, use bam below)
    fastqs:
      - path/to/1.fq
      - path/to/2.fq
    # Path to bam with the reads used for variant calling (alternatively, use fastqs above)
    # If both are given, bam is used.
    # The bam is assumed to be already duplicate-marked, sorted, and indexed.
    bam: path/to/sample.bam
    target-regions: path/to/regions.bed
    # whether given target regions are on hg19
    grch37: false

# Optional for testing: limit to first 10000 reads
limit-reads: false

# whether evaluation shall happen on grch37
grch37: false