variant-calls:
  # Listing of callsets and corresponding paths, representing variant call results
  # from different pipelines or different configurations of the same pipeline.
  # Multiple entries are possible.
  <callset>: 
    path: <path>
    # benchmark to use (giab-NA12878-exome or any custom benchmark name provided from below)
    benchmark: giab-na12878-exome
    # Uncomment and point to file containing contig name replacements
    # as needed for 'bcftools annotate --rename-chrs'
    # rename-contigs: path/to/rename-contigs.txt

# Optional custom benchmarks
custom-benchmarks:
  my-custom-benchmark: # custom benchmark name, choose freely (no whitespace allowed)
    # Truth genome to consider (for now only NA12878 allowed, TODO: CHM)
    genome: na12878
    fastqs:
      - path/to/1.fq
      - path/to/2.fq
    target-regions: path/to/regions.bed
    # whether given target regions are on hg19
    grch37: false

# Optional for testing: limit to first 10000 reads
limit-reads: false

# whether evaluation shall happen on grch37
grch37: false