variant-calls:
  # Listing of callsets and corresponding paths, representing variant call results
  # from different pipelines or different configurations of the same pipeline.
  # Multiple entries are possible.
  <callset>: <path>