__use_yte__: true

__variables__:
  green: "#74c476"
  orange: "#fd8d3c"
#  labels: ?params.labels

name: ?f"{wildcards.classification} of"

webview-controls: true
default-view: results-table

datasets:
  results:
    path: ?input.table
    separator: "\t"
    # offer-excel: true
    # links:
    #   link to table:
    #     column: callset
    #     table-row: results-table/callset

views:
  results-table:
    dataset: results
    # desc: |
    #   ?f"""
    #    Benchmark version: {params.genome} {params.version}
    #   """
    page-size: 12
    render-table:
      columns:
        coverage:
          plot:
            heatmap:
              scale: ordinal
        # sort_index:
        #   display-mode: hidden
        # ?if params.somatic:
        #   true_genotype:
        #     display-mode: hidden
        #   predicted_genotype:
        #     display-mode: hidden