__use_yte__: true

__variables__:
  green: "#74c476"
  orange: "#fd8d3c"
  labels: ?params.labels

name: ?f"{wildcards.classification} of {wildcards.benchmark}"

webview-controls: true
default-view: results-table

datasets:
  results:
    path: ?input.table
    separator: "\t"
    offer-excel: true
    links:
      link to table:
        column: callset
        table-row: results-table/callset

views:
  results-table:
    dataset: results
    # desc: |
      # ?f"""
      #  Benchmark version: {params.genome} {params.version}
      # """
    page-size: 12
    render-table:
      headers:
        ?for i, label in enumerate(labels):
          ?i + 1:
            label: ?label
            ellipsis: 4
            plot:
              heatmap:
                scale: ordinal
                color-scheme: category20