__variables__:
  green: "#74c476"
  orange: "#fd8d3c"

name: ?f"Precision/recall analysis of {wildcards.benchmark}"

webview-controls: true
default-view: results-table

datasets:
  results:
    path: ?input.dataset
    separator: "\t"
    links:
      link to table:
        column: callset
        table-row: results-table/callset

views:
  results-plot:
    dataset: results
    desc: |
      Precision and recall are calculated by matching variants between each callset 
      and truth, stratified by coverage categories. The matching ignores genotype
      differences. Instead, genotype mismatches are displayed in the "genotype mismatch rate" 
      column of the tabular result representation or in the tooltips shown when hovering
      a point.

      Data points with less than 50 observations for recall (TP + FN) or precision (TP + FP)
      are not shown because estimates are unreliable in such cases.

      Zoom in by scrolling inside of the plot area, pan by dragging, and reset by double-clicking.
    render-plot:
      spec: |
        {
          "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
          "description": "Precision/recall plot for all callsets.",
          "width": 600,
          "height": 600,
          "params": [{
            "name": "grid",
            "select": "interval",
            "bind": "scales"
          }],
          "transform": [
            {
              "filter": "((datum.tp_truth + datum.fn) >= 50) & ((datum.tp_query + datum.fp) >= 50)"
            }
          ],
          "mark": {
            "type": "line",
            "point": true,
            "tooltip": {"content": "data"}, "clip": true
          },
          "encoding": {
            "x": {"field": "recall", "type": "quantitative"},
            "y": {"field": "precision", "type": "quantitative"},
            "color": {
              "field": "callset",
              "type": "nominal",
              "scale": {"scheme": "category20"}
            },
            "order": {"field": "sort_index", "type": "quantitative"},
            "href": {"field": "link to table"}
          }
        }

  results-table:
    dataset: results
    ?if params.vaf:
      desc: |
        Precision and recall are calculated by matching variants between each callset 
        and truth, stratified by coverage categories. Stratified by VAF.
      page-size: 12
      render-table:
        columns:
          callset:
            plot:
              heatmap:
                scale: ordinal
                color-scheme: category20
          precision:
            precision: 3
            plot:
              ticks:
                scale: linear
          recall:
            precision: 3
            plot:
              ticks:
                scale: linear
          coverage:
            plot:
              heatmap:
                scale: ordinal
                domain:
                  - low
                  - medium
                  - high
                range:
                  - "#c6dbef"
                  - "#9ecae1"
                  - "#6baed6"
          vaf:
            plot:
             heatmap:
                scale: linear
                # domain:
                #   - <10%
                #   - <20%
                #   - <30%
                #   - <40%
                #   - <50%
                #   - <60%
                #   - <70%
                #   - <80%
                #   - <90%
                #   - <=100%
                color-scheme: greens
    ?else:
      desc: |
        Precision and recall are calculated by matching variants between each callset 
        and truth, stratified by coverage categories. The matching ignores genotype
        differences. Instead, genotype mismatches are displayed in the "genotype mismatch rate" 
        column.
      page-size: 12
      render-table:
        columns:
          callset:
            plot:
              heatmap:
                scale: ordinal
                color-scheme: category20
          precision:
            precision: 3
            plot:
              ticks:
                scale: linear
          recall:
            precision: 3
            plot:
              ticks:
                scale: linear
          genotype_mismatch_rate:
            ?if params.somatic:
              display-mode: hidden
            ?else:
              display-mode: normal
            precision: 3
            plot:
              ticks:
                scale: linear
          coverage:
            plot:
              heatmap:
                scale: ordinal
                domain:
                  - low
                  - medium
                  - high
                range:
                  - "#c6dbef"
                  - "#9ecae1"
                  - "#6baed6"