__definitions__:
  - import pandas as pd
  - columns = pd.read_table(input.dataset, sep="\t", nrows=1).columns
__variables__:
  dataset_name: ?f"{wildcards.type}-calls"

name: ?f"Subset of {wildcards.type} calls at loci with {wildcards.cov} coverage on genome {wildcards.genome} for all callsets."

datasets:
  ?dataset_name:
    path: ?input.dataset
    separator: "\t"

views:
  ?dataset_name:
    dataset: ?dataset_name
    page-size: 50
    render-table:
      true_genotype:
        plot:
          heatmap:
            scale: ordinal
            color-scheme: category10
      ?for callset in columns[5:]:
        ?callset:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
              aux-domain-columns: ?list(columns[5:])