variant-calls:
  dummy: 
    path: "resources/variants/NA12878.truth.vcf"
    benchmark: "giab-NA12878-exome"

custom-benchmarks:
  my-custom-benchmark: # custom benchmark name, choose freely (no whitespace allowed)
    # Truth genome to consider (for now only NA12878 allowed, TODO: CHM)
    genome: NA12878
    fastqs:
      - path/to/1.fq
      - path/to/2.fq
    target-regions: path/to/regions.bed
    # whether given target regions are on hg19
    grch37: false

limit-regions:
  activate: true
  bed: config/limit-regions.bed

grch37: false