variant-calls:
  dummy: "resources/variants/truth.vcf"

custom-reads:
  activate: false
  fastqs:
    - path/to/1.fq
    - path/to/2.fq
  target-regions: path/to/regions.bed
  grch37: false

limit-regions:
  activate: true
  bed: config/limit-regions.bed

grch37: false